//i wrote, IC polished

const page1Content = `
<h2>1</h2>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Todd Brian Davidson stares blearily into the dark.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He cannot sleep. How could he, knowing its HIS fault his best friend is missing. There&rsquo;s only so much guilt the average person can have in a situation like his, but his still-dry mouth and sunken eyes remind him his experiences are not universal.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He never should&rsquo;ve told him about the Killer. About the mysterious riddles left behind. About the bodies and how they were mangled. The disappearances.&nbsp;</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Especially the disappearances.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He should have known, beyond any doubt, that Wodin would obsess over it. It&rsquo;s almost like it was made just&hellip; to trap him. That tantalizing combination of esoteric hints and internet friendly answers. The perfect crime for a bunch of Gomart-two-dollar-hatted backseat internet sleuths to obsess over.&nbsp; Simple, bite-sized, consumable. Radio-dramable.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He should&rsquo;ve known better than to trust a media circus: whatever it is, they always want more.</span></p>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">There&rsquo;s only so much thread of his own misery he can pull before his eyes flutter closed, and he begins his fitful rest. Bathed in that cold nothing, encroaching upon him from the space behind his eyes, he dreams the same dream of the Mountain he&rsquo;s had every night for as long as he can remember.</span></p>
`

const page2Content = `
<h2>2</h2>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Witness stares blearily into the kaleidoscope landscape.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Even now, his eyes have not become accustomed to the sky folding into the land folding into the sky-- a "custom shader" , the jagged spiraling creature who used to be one of his bosses assured him, her smile all teeth.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Perhaps too many teeth, in retrospect. The fractal nature of the universe seems to assure that.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Thinking about it is meaningless, though. Time is meaningless. In this land of forever there&rsquo;s only forever, stretching in all directions, but still he can feel the throes of age seep into his bones. Mental acuity is the one thing that is eternal, he guesses. Experiences. Those hide in the closets of your mind, but they don&rsquo;t fade.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He has experienced wonders and horrors only Skyrim modders can dream of, and somehow all he feels is tired.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Behind him, he feels the presence of one of the few friends left to him, warm and inviting. Or perhaps he just feels that due to the absence of his other friend. He never likes this place at room temperature.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Rest, Child,&rdquo; she speaks into his ear, with as much authority as there is love.&nbsp; &ldquo;Let your Loop End."</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He closes his eyes and doesn't feel a thing ever again.</span></p>`;

const page3Content = `
<h2>3</h2>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Until, finally, he does.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">When he wakes-- or at least, when he&rsquo;s aware of what&rsquo;s around him-- he&rsquo;s staring into his coffee as if it&rsquo;s leftover laundry. The house he&rsquo;s in is bathed in tasteful decor, inoffensive and plain, and uniformly bathed in whites and grays. One could not be blamed if they believed that apartment was a stage prop for a documentary on minimalism.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Fuck this arm. He hates it. Always has. The peace, the </span><em><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">normalcy</span></em><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> of it all, tastes like ashes in his mouth. A cruel parody of the life he would have had with Wodin.&nbsp;</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Not like he&rsquo;s stupid, either. He </span><em><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">knows</span></em><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> why Wanda can't be here with him.&nbsp; Of course he does.&nbsp; Until she finally accepts that things can change, she is stuck repeating those same fifty years she thought she was promised, forever. And until she does&hellip;</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Well, he&rsquo;s here. Giving a mean stare to hand-poured coffee.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He sighs.&nbsp; The man across from him politely clears his throat.&nbsp;&nbsp;</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Rough Night?" Witherby asks, his stare peeking out of a newspaper he&rsquo;s skimming.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Night?</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Oh&hellip; it's a pun. He's unsure whether he&rsquo;s doing it on purpose or just let it slip-- either way, not going to acknowledge it. He gives a nonchalant shrug instead, returning his gaze. "Getting out of Arm2 is never </span><em><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">fun</span></em><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, but I'm not gonna blame the Doc for it."</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"I had not heard we were beyond casting blame, now.&rdquo; His eyes are on the newspaper again, his words trailed to a mumble. &ldquo;Especially about people like </span><em><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">her</span></em><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.&rdquo;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"This again?&rdquo; The Witness groans. &ldquo;Can we just--- can we agree to disagree here? You guys are my only friends. Not a lot of people who remember the whole &lsquo;everything loops forever&rsquo; bit of the equation." His hands raise air quotes, just for emphasis.</span></p>
<p style="line-height: 1.38; text-align: center; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&ldquo;Could talk to Parker,&rdquo; Witherby posits.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&ldquo;You </span><em><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">know</span></em><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Parker doesn&rsquo;t count.&rdquo;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The man in front of him gives this some thought, his eyes closing in thought. When he opens them again he calmly folds his newspaper, setting it aside on the table next to them; he was likely never actually reading it, the Witness guesses. Just scanning it for future conversation topics.&nbsp;</span></p>

`

const page4Content = `

<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"A fair point,&rdquo; he says. He pauses for a moment before he continues. &ldquo;At the very least, I recommend that we talk about the garish, two-cent suit that NAM is always wearing."</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Witness cracks a smile. "You mean how he has the elbow patches even though his Dad could afford to buy the entire sweatshop?"</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The man lets out a thoughtful &lsquo;hm&rsquo;. &ldquo;I don&rsquo;t think his dad would ever let the peasantry breathe on his son&rsquo;s garments.&rdquo;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&ldquo;Maybe it&rsquo;s all machines,&rdquo; the Witness chides. &ldquo;Isn&rsquo;t he an ethics professor? That&rsquo;d make for a good lesson.&rdquo;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&ldquo;On the values of manual labor?&rdquo;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&ldquo;Nah. On the values of nepotism.&rdquo;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Witherby smiles back, closed-lipped but earnest, the warmth of it as startling as a flower peeking out from under ice. "I knew there was a reason I hung out with you."</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Witness hums.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Maybe, just maybe, he can tolerate this arm for a measly 80 years more.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">And thus, the conversation went on, as did the days, the weeks, the months. With plenty of people and plenty of hardships, life blended together in that pleasant way that only peace can assure, and that only the gift of monotony can give.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Eventually, old, and at peace, the Witness closes his eyes for the final time in this Universe.&nbsp;</span></p>

`;

const page5Content = `
<h2>4</h2>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The God of Witnessing opens his eyes and eyes and eyes. Hundreds stare up at him in fear and devotion. He feels awake, properly awake, for the first time in centuries. He needs to go. To find out who else is awake--</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><em><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Pssssssst</span></em><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A harsh sound calls to attention from crack on the dais he&rsquo;s resting in.&nbsp;&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"PSSSSSST!!!!"</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Yes, Parker?" he says in a voice that echoes with the weight of an eternity of Watching. The crowds murmur. Their god awakens.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Parker pops his surreally still human head out of the marble.&nbsp; "Hey! Have you seen Vik?"</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Witness considers. He will only be fully awake for a little while before he fades back into the God Throes this universe forces on all those who Loop. Does he really want to spend his time breaking the fourth wall with Parker?&nbsp; He supposes the odds of Fiona or Witherby being awake and coherent at the same time as him are low. This will do, as a diversion.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Have you lost them?" The crowds are writing down his every word.&nbsp; Generations will live and die by the edicts he is proclaiming here.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Parker makes a whining sound in the back of his throat, followed by a coughing fit. "It's hard to keep track of a spreading mass of mold and rot! Come on! Witness! Buddy, be a bro! I wouldn't ask if I thought it was gonna affect the STORY!"</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"An Eye for an Eye, Parker. I will Look for them. But first, you must tell me three good qualities the Lord of Space has."&nbsp; The crowd begins chanting "an eye for an eye for an eye for an eye". They always like that.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Parker scowls and pulls his head back into the earth. Muffled though it is, the Witness can clearly make out the whining "Do I HAVE to!?".&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Witness is patient. He has no choice. Eternity is his gift for spurning the confines of 50 years. An Eternity without her.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"Parker. She is the only reason you met Vik. The only reason you have gained some semblance of control of your curse. And she makes anime get popular decades before it otherwise would."</span></p>
`;

const page6Content = `
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Buried Man growls from beneath the earth.&nbsp; "And if she LET me loose I could TAKE my bestie and go somewhere better! We could run a COFFEE shop together Witness, a COFFEE shop!"</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Witness stares down at the crack in the earth and the two gleaming eyes within.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"You have already escaped, Thief. Wanda is not here. Wanda can not be here. She is trapped in the event horizon of her own making. " the crowds are clapping their hands over their ears, blood flowing freely.&nbsp; The Name&nbsp; had been too much for them to bear. The Witness feels the stirrings of regret in causing them harm, but can not bring himself to truly care about beings so ephemeral.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">"And if you believe THAT I have a bridge to sell you. Its underground. Only slightly used. I may have stolen a bridge. Witness, do you want to buy a bridge?"</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The Witnesses eyes and eyes and eyes are growing heavy. No. It's too soon. He's barely been awake this time. His talons lock into position on the dais, his skin grows hard and cold. A statue once more, he stares out and out and out at the bleeding crowd and the pleading man.</span></p>
</p>`;


const page7Content = `
<h2>1</h2><p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Todd Brian Davidson opens his eyes and is momentarily disoriented to only have the two. He knows he slept.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He must have slept.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He dreamt...its hard to remember, dreams always are, but they always feel so long.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">So important.</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">He misses Wodin with an intensity that surprises him and resolves to try knocking on his door again today.&nbsp;&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Maybe. Maybe he's back. From wherever he went. Maybe everything is fine. Maybe. Maybe this "Wanda" he thinks about so much in his dreams doesn't have to exist.&nbsp;</span></p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.38; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Maybe.</span></p>`;


class Page {
  number;
  content;
  constructor(number, content){
    this.number = number;
    this.content = content;
  }

  render = (ele)=>{
    //make a div, add to parent, add dirt graphics.
    const me = document.createElement("div");
    me.className =(`page`);
    me.innerHTML = this.content;
    const bg = document.createElement("div");
    bg.className=`page${this.number}`;
    me.append(bg)
    ele.append(me);
  }
}

